version: "3"

services:
  redis:
    image: 'redislabs/rejson:latest'
    entrypoint: "redis-server --appendonly yes --loadmodule /usr/lib/redis/modules/rejson.so"
    ports:
      - 6379:6379
    volumes:
      - data:/data
  app:
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    links:
      - redis
    depends_on:
      - redis
volumes:
  data:
